/**
 * SCORM Bridge - Connects postMessage from iframe to LMS API
 * Generated by CourseCode - Do not edit manually
 * 
 * Uses pipwerks with the package-declared SCORM version.
 */

// Import pipwerks (bundled with proxy package)
// Note: pipwerks is loaded as a global in the proxy package
// We check for it and initialize on load

(function() {
    'use strict';

    // Wait for pipwerks to be available
    if (typeof pipwerks === 'undefined') {
        console.error('SCORM Bridge: pipwerks not loaded');
        return;
    }

    const scorm = pipwerks.SCORM;
    const iframe = document.getElementById('course');
    let initialized = false;
    let sessionStartedAt = 0;
    let courseOrigin = null;

    const baseFormat = window.COURSECODE_PROXY_CONFIG?.baseFormat;
    if (baseFormat !== 'scorm1.2' && baseFormat !== 'scorm2004') {
        console.error('SCORM Bridge: Invalid or missing base format; bridge disabled');
        return;
    }
    scorm.version = baseFormat === 'scorm1.2' ? '1.2' : '2004';

    // Validate the configured launch URL itself. The actual post-redirect course
    // origin is securely bound by a nonce handshake with iframe.contentWindow.
    try {
        const courseUrl = window.COURSECODE_PROXY_CONFIG?.courseUrl;
        if (!courseUrl) throw new Error('Missing proxy course URL');
        console.log('SCORM Bridge: Configured course origin:', new URL(courseUrl).origin);
    } catch (e) {
        console.error('SCORM Bridge: Invalid course URL; bridge disabled:', e.message);
        return;
    }

    // Disable pipwerks auto-handling - we manage status ourselves
    scorm.handleCompletionStatus = false;
    scorm.handleExitMode = false;

    function formatSessionTime() {
        const totalSeconds = Math.max(0, Math.floor((Date.now() - sessionStartedAt) / 1000));
        const hours = Math.floor(totalSeconds / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const seconds = totalSeconds % 60;
        if (baseFormat === 'scorm1.2') {
            return `${String(hours).padStart(4, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
        }
        return `PT${hours ? `${hours}H` : ''}${minutes ? `${minutes}M` : ''}${seconds || (!hours && !minutes) ? `${seconds}S` : ''}`;
    }

    function stageEmergencySessionData() {
        if (!initialized) return;
        const exitKey = baseFormat === 'scorm1.2' ? 'cmi.core.exit' : 'cmi.exit';
        const sessionTimeKey = baseFormat === 'scorm1.2' ? 'cmi.core.session_time' : 'cmi.session_time';
        scorm.set(exitKey, 'suspend');
        scorm.set(sessionTimeKey, formatSessionTime());
    }

    /**
     * Handle messages from course iframe
     */
    window.addEventListener('message', function(event) {
        const { data } = event;

        if (data?.type === 'scorm-proxy-handshake') {
            if (!iframe || event.source !== iframe.contentWindow || !data.nonce) return;
            if (data.baseFormat !== baseFormat) {
                console.warn('SCORM Bridge: Rejected course with mismatched SCORM format');
                return;
            }

            courseOrigin = event.origin;
            event.source.postMessage({
                type: 'scorm-proxy-handshake-response',
                nonce: data.nonce,
                baseFormat
            }, courseOrigin);
            return;
        }

        // Ignore non-proxy messages
        if (!data || data.type !== 'scorm-proxy-request') {
            return;
        }

        if (!iframe || event.source !== iframe.contentWindow) {
            console.warn('SCORM Bridge: Rejected message not sent by the course iframe');
            return;
        }

        // Requests are accepted only after the handshake and only from the
        // exact origin that owns the configured iframe window.
        if (!courseOrigin || event.origin !== courseOrigin) {
            console.warn('SCORM Bridge: Rejected message from unexpected origin:', event.origin);
            return;
        }

        const { id, method, args = [] } = data;
        let result;
        let error = null;

        try {
            switch (method) {
                case 'Initialize':
                    if (!initialized) {
                        result = scorm.init();
                        initialized = result;
                        if (initialized) sessionStartedAt = Date.now();
                    } else {
                        result = true;
                    }
                    break;

                case 'GetValue':
                    result = scorm.get(args[0]);
                    break;

                case 'SetValue':
                    result = scorm.set(args[0], args[1]);
                    break;

                case 'Commit':
                    result = scorm.save();
                    break;

                case 'Terminate':
                    result = scorm.quit();
                    initialized = false;
                    break;

                case 'EmergencySave':
                    if (initialized) stageEmergencySessionData();
                    result = initialized ? scorm.save() : false;
                    break;

                default:
                    error = `Unknown method: ${method}`;
            }
        } catch (e) {
            error = e.message || String(e);
            console.error('SCORM Bridge error:', method, e);
        }

        const shouldInspectLmsError = method === 'GetValue' || result === false || result === 'false';
        if (!error && shouldInspectLmsError) {
            const code = Number(scorm.debug?.getCode?.() || 0);
            if (code !== 0) {
                error = `SCORM ${method} failed (${code}): ${scorm.debug?.getInfo?.(code) || 'Unknown LMS error'}`;
            }
        }

        // Send response back to iframe (targeted to known origin)
        if (id !== null && id !== undefined && iframe && iframe.contentWindow) {
            iframe.contentWindow.postMessage({
                type: 'scorm-proxy-response',
                id,
                result,
                error
            }, courseOrigin);
        }
    });

    // The LMS-side page is the only context guaranteed to still have direct,
    // synchronous API access when a browser tears down the external iframe.
    window.addEventListener('pagehide', function() {
        if (!initialized) return;
        try {
            stageEmergencySessionData();
            scorm.save();
            scorm.quit();
        } catch (error) {
            console.error('SCORM Bridge: Emergency pagehide finalization failed:', error);
        } finally {
            initialized = false;
        }
    });

    // Log bridge ready
    console.log('SCORM Bridge: Ready for ' + baseFormat + ' (pipwerks v' + (pipwerks.version || '1.x') + ')');

})();
