/**
 * SCORM Bridge - Connects postMessage from iframe to LMS API
 * Generated by CourseCode - Do not edit manually
 * 
 * Uses pipwerks wrapper which auto-detects SCORM 1.2 or 2004 API.
 */

// Import pipwerks (bundled with proxy package)
// Note: pipwerks is loaded as a global in the proxy package
// We check for it and initialize on load

(function() {
    'use strict';

    // Wait for pipwerks to be available
    if (typeof pipwerks === 'undefined') {
        console.error('SCORM Bridge: pipwerks not loaded');
        return;
    }

    const scorm = pipwerks.SCORM;
    const iframe = document.getElementById('course');
    let initialized = false;

    // Derive the exact expected course origin from build-time configuration.
    // Fail closed: wildcard origins would allow unrelated frames to operate the LMS API.
    let courseOrigin;
    try {
        const courseUrl = window.COURSECODE_PROXY_CONFIG?.courseUrl;
        if (!courseUrl) throw new Error('Missing proxy course URL');
        courseOrigin = new URL(courseUrl).origin;
        console.log('SCORM Bridge: Expected course origin:', courseOrigin);
    } catch (e) {
        console.error('SCORM Bridge: Invalid course URL; bridge disabled:', e.message);
        return;
    }

    // Disable pipwerks auto-handling - we manage status ourselves
    scorm.handleCompletionStatus = false;
    scorm.handleExitMode = false;

    /**
     * Handle messages from course iframe
     */
    window.addEventListener('message', function(event) {
        const { data } = event;

        // Ignore non-proxy messages
        if (!data || data.type !== 'scorm-proxy-request') {
            return;
        }

        if (!iframe || event.source !== iframe.contentWindow) {
            console.warn('SCORM Bridge: Rejected message not sent by the course iframe');
            return;
        }

        // Validate origin when we have a known course origin
        if (event.origin !== courseOrigin) {
            console.warn('SCORM Bridge: Rejected message from unexpected origin:', event.origin);
            return;
        }

        const { id, method, args = [] } = data;
        let result;
        let error = null;

        try {
            switch (method) {
                case 'Initialize':
                    if (!initialized) {
                        result = scorm.init();
                        initialized = result;
                    } else {
                        result = true;
                    }
                    break;

                case 'GetValue':
                    result = scorm.get(args[0]);
                    break;

                case 'SetValue':
                    result = scorm.set(args[0], args[1]);
                    break;

                case 'Commit':
                    result = scorm.save();
                    break;

                case 'Terminate':
                    result = scorm.quit();
                    initialized = false;
                    break;

                default:
                    error = `Unknown method: ${method}`;
            }
        } catch (e) {
            error = e.message || String(e);
            console.error('SCORM Bridge error:', method, e);
        }

        // Send response back to iframe (targeted to known origin)
        if (iframe && iframe.contentWindow) {
            iframe.contentWindow.postMessage({
                type: 'scorm-proxy-response',
                id,
                result,
                error
            }, courseOrigin);
        }
    });

    // Log bridge ready
    console.log('SCORM Bridge: Ready (pipwerks v' + (pipwerks.version || '1.x') + ')');

})();
